#!/usr/bin/zsh

#################
## Shell Setup ##
#################

# Zinit config
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [ ! -d $ZINIT_HOME ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "${ZINIT_HOME}"
fi

source "${ZINIT_HOME}/zinit.zsh"

# Load zinit plugins
zinit wait lucid for \
  atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
  blockf \
    zsh-users/zsh-completions \
  atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions


autoload -U compinit && compinit

# Set $PATH if ~/.local/bin exist
if [ -d "$HOME/.local/bin" ]; then
  typeset -U path PATH
  path=($HOME/.local/bin $path)
  export PATH
fi
# Set $PATH if ~/go/bin exist
if [ -d "$HOME/go/bin" ]; then
  typeset -U path PATH
  path=($HOME/go/bin $path)
  export PATH
fi

# zsh config vars
ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/"
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zhistory"
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTDUP=erase
# do not highlight pasted text
zle_highlight=('paste:none')

# Load Theme
[[ -e "$ZDOTDIR/themerc" ]]   && source "$ZDOTDIR/themerc"
# Load Functions
[[ -e "$ZDOTDIR/funcrc" ]]    && source "$ZDOTDIR/funcrc"
# Load Arch Linux Config
[[ -e "$ZDOTDIR/archrc" ]]    && source "$ZDOTDIR/archrc"
# Load Mac Config
[[ -e "$ZDOTDIR/macrc" ]]     && source "$ZDOTDIR/macrc"
# Load Environment Variables
[[ -e "$ZDOTDIR/envrc" ]]     && source "$ZDOTDIR/envrc"
# Load aliases
[[ -e "$ZDOTDIR/aliasrc" ]]   && source "$ZDOTDIR/aliasrc"
# Load Keybindings
[[ -e "$ZDOTDIR/keybindrc" ]] && source "$ZDOTDIR/keybindrc"

# Set Fast Syntax Highlighting Theme # The sed command removes the color codes
theme_name=$(echo $(fast-theme -s) | awk -F': ' '{print $2}' | awk '{print $1}' | sed -e 's/\x1b\[[0-9;]*m//g')
[[ "$theme_name" != "catppuccin-mocha" ]] && \
fast-theme XDG:catppuccin-mocha

# ZSH config
setopt extended_glob                    # Extended globbing. Allows using regular expressions with *
setopt no_case_glob                     # Case insensitive globbing
setopt rc_expand_param                  # Array expension with parameters
setopt no_check_jobs                    # Don't warn about running processes when exiting
setopt numeric_glob_sort                # Sort filenames numerically when it makes sense
setopt no_beep                          # Disable beep
setopt auto_cd                          # Automatically cd into a directory if it's the only argument

# ZSH History
setopt appendhistory                    # Append history to the history file
setopt sharehistory                     # Share history between all sessions
setopt hist_ignore_space                # Ignore commands that start with a space
setopt hist_ignore_all_dups             # Remove all duplicates from history
setopt hist_save_no_dups                # Don't save duplicates in history
setopt hist_ignore_dups                 # Ignore duplicates in history
setopt hist_find_no_dups                 # Don't display duplicates when searching history

#TODO: This still needs work to improve fzf-tab completions
# case-insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'
# automatically find new executables in path
zstyle ':completion:*' rehash true
#
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:complete:cd:*' popup-pad 30 0

#zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion::complete:*' gain-privileges 1
# Speed up completions
zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion:*' use-cache on
# Load Completions
autoload -Uz compinit && compinit


#####################
## LOAD Everything ##
#####################

# Run neofetch
fastfetch

# Load Direnv
eval "$(direnv hook zsh)"

# Load zoxide
eval "$(zoxide init --cmd cd zsh)"

# Load Starship
eval "$(starship init zsh)"

#############
##   EOF   ##
#############
