# Start Utilities and Services for Desktop
exec-once = hyprpaper & waybar & udiskie & dunst & #avizo-service &

# Clipboard
exec-once = wl-paste -p --watch wl-copy -pc && wl-paste --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
# Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1
# Swayidle
#exec-once = swayidle -w timeout 1800 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' timeout 5400 'systemctl suspend' before-sleep 'swaylock -f -c 000000' &
# Keyring
exec-once = dbus-update-activation-environment --systemd --all
exec-once = gnome-keyring-daemon --start --components=secrets
