
splash = false
ipc = off

#if more than one preload is desired then continue to preload other backgrounds
preload = ~/.config/wallpaper/unix1.jpg

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = ,~/.config/wallpaper/unix1.jpg
