
splash = false
ipc = off

#if more than one preload is desired then continue to preload other backgrounds
preload = ~/Pictures/Wallpapers/arch1.jpg
preload = ~/Pictures/Wallpapers/arch2.png
preload = ~/Pictures/Wallpapers/arch3.jpg
preload = ~/Pictures/Wallpapers/arch4.jpg
preload = ~/Pictures/Wallpapers/arch5.jpg
preload = ~/Pictures/Wallpapers/arch6.jpg
preload = ~/Pictures/Wallpapers/arch7.jpg
preload = ~/Pictures/Wallpapers/arch8.jpg
preload = ~/Pictures/Wallpapers/arch9.jpg
preload = ~/Pictures/Wallpapers/arch10.jpg
preload = ~/Pictures/Wallpapers/arch11.png
preload = ~/Pictures/Wallpapers/city.jpg
preload = ~/Pictures/Wallpapers/dracula-arch.png
preload = ~/Pictures/Wallpapers/dracula-background.png
preload = ~/Pictures/Wallpapers/dracula-pro.png
preload = ~/Pictures/Wallpapers/unix-1.jpg
preload = ~/Pictures/Wallpapers/arch12.jpg

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = DP-2,~/Pictures/Wallpapers/arch12.jpg
wallpaper = DP-1,~/Pictures/Wallpapers/arch12.jpg
