
#if more than one preload is desired then continue to preload other backgrounds
preload = ~/Pictures/Wallpapers/desktop-2560x1600.png

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = DP-2,~/Pictures/Wallpapers/desktop-2560x1600.png
wallpaper = DP-1,~/Pictures/Wallpapers/desktop-2560x1600.png
