#!/usr/bin/bash

#############
## aliases ##
#############





# Get fastest mirrors
alias drop-caches='sudo paccache -rk3; paru -Sc --aur --noconfirm'
alias update-mirrors='export TMPFILE="$(mktemp)"; \
    sudo true; \
    rate-mirrors --save=$TMPFILE arch --disable-comments-in-file --entry-country=CA --protocol=https --max-delay=7200 \
      && sudo mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist-backup \
      && sudo mv $TMPFILE /etc/pacman.d/mirrorlist \
      && drop-caches \
      && paru -Syyu --noconfirm'

# Bat colorizing pager for help
alias -g -- -h='-h 2>&1 | bat --language=help --plain'
alias -g -- --help='--help 2>&1 | bat --language=help --plain'
