#!/usr/bin/bash

################
## Arch Linux ##
################

# Path to zsh plugins
zplug="/usr/share/zsh/plugins"

# fzf-tab
[[ -e "$zplug/fzf-tab-git/fzf-tab.plugin.zsh" ]] && \
source "$zplug/fzf-tab-git/fzf-tab.plugin.zsh"

# fast syntax highlighting
[[ -e "$zplug/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh" ]] && \
source "$zplug/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"

# autosuggestion
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
[[ -e "$zplug/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"  ]] && \
source "$zplug/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"

# history substring search
[[ -e "$zplug/zsh-history-substring-search/zsh-history-substring-search.zsh" ]]  && \
source "$zplug/zsh-history-substring-search/zsh-history-substring-search.zsh"

# fzf
[[ -e /usr/share/fzf/key-bindings.zsh ]] && \
source /usr/share/fzf/key-bindings.zsh
[[ -e /usr/share/fzf/completion.zsh ]] && \
source /usr/share/fzf/completion.zsh

# zoxide
[[ -e "$zplug/zoxide/init.zsh" ]] && \
source "$zplug/zoxide/init.zsh"

# command-not-found
[[ -e /usr/share/doc/pkgfile/command-not-found.zsh ]] && \
source /usr/share/doc/pkgfile/command-not-found.zsh

# bun completions
[ -s "$HOME/.local/share/reflex/bun/_bun" ] && \
source "$HOME/.local/share/reflex/bun/_bun"
