#!/usr/bin/bash

#########
## env ##
#########

# With out this Starship shifts the prompt over 2 chars when pressing tab.
export LC_ALL="en_CA.UTF-8"

# eza (ls replacement)
export eza_params=('--git' '--icons' '--classify' '--group-directories-first' '--group')

# FZF
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--multi"


if ! command -v nvim 2>&1 >/dev/null; then
    export EDITOR='nvim'
else
    export EDITOR='vim'
fi
export VISUAL='code --wait'

# Bat colorizing pager for manpages
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANROFFOPT="-c"
