#!/usr/bin/bash

###############
## Functions ##
###############

# Set Window Title
function set_win_title(){
    echo -ne "\033]0; $USER@$HOST:${PWD/$HOME/~} \007"
}
precmd_functions+=(set_win_title)

# Image Manipulation remove exif data
function cimg(){
    exiftool -overwrite_original -all= $1
}

# Docker Compose
## Start attached
function dcup() {
    if [ $1 ]; then
        docker-compose -f $1 up --build
    else
        docker-compose up --build
    fi
}
## Start Detached
function dcupd() {
    if [ $1 ]; then
        docker-compose -f $1 up --build -d
    else
        docker-compose up --build -d
    fi
}

