#!/usr/bin/bash

#############
## Keybind ##
#############

# Use emacs key bindings
# bindkey -e
# bindkey '^p' history-search-backward
# bindkey '^n' history-search-forward
# bindkey '^?' backward-delete-char
