[General]
__userfile__=true

[Environment]
LANG=en_CA.UTF-8
LC_COLLATE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_MONETARY=en_CA.UTF-8
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8

[Mouse]
cursor_size=24
cursor_theme=Dracula-cursors
