# Get editor completions based on the config schema
"$schema"='https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette="catppuccin_mocha"

# Layout the prompt with custom format
# Missing \ at the end of some lines is intentional, the \ escapes the linebroak.
format="""
$username\
$os\
$hostname\
$directory
$python\
$golang\
$rust\
$lua\
$c\
$zig\
$dart\
$swift\
$nodejs\
$haskell\
$git_branch\
$git_status
$sudo\
$character\
"""

right_format="""
$cmd_duration\
$jobs\
$direnv\
$docker_context\
"""

#################
## Prompt Line ##
#################
# sudo and Prompt character

[sudo]
format  ="[$symbol]($style) "
style   ="italic mauve"
symbol  ="󱦚"
disabled=false

[character]
format        ="$symbol "
success_symbol="[ ❯](green)"
error_symbol  ="[ ❯](red)"
vimcmd_symbol ="[ ❯](sky)"
# not supported in zsh
vimcmd_replace_one_symbol="R1"
vimcmd_replace_symbol    ="R"
vimcmd_visual_symbol     ="V"

################
##  Line one  ##
################
# User, OS, Hostname, and Directory

[username]
format     ="[$user]($style) "
style_user ="italic green"
style_root ="italic red"
show_always=true
disabled   =false

[os]
format  ="[$symbol](rosewater) "
disabled=false

[hostname]
format  ="[$hostname](lavender) "
ssh_only=false
disabled=false

[directory]
format           ="[$path]($style)[$read_only]($read_only_style) "
home_symbol      ="󱂵 Home"
truncation_symbol=" /"
read_only        =" 󰌾"
read_only_style  ="red"
use_os_path_sep  =true
style            ="italic peach"
disabled         =false

# Line Break here

################
##  Line two  ##
################
# Language versions, tools, and git.

[python]
format        ='[(${symbol}(${version} \($virtualenv\)))]($style) '
symbol        =" "
version_format="${raw}"
style         ="italic teal"
disabled      =false

[golang]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic sky"
disabled      =false

[rust]
format        ="[$symbol$version]($style) "
symbol        ="󱘗 "
version_format="${raw}"
style         ="italic maroon"
disabled      =false

[lua]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic peach"
disabled      =false

[c]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic flamingo"
disabled      =false

[zig]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic flamingo"
disabled      =false

[dart]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic sapphire"
disabled      =false

[swift]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic red"
disabled      =false

[nodejs]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic green"
detect_files  =[ "package-lock.json", "yarn.lock" ]
detect_folders=[ "node_modules" ]
disabled      =false

[haskell]
format        ="[$symbol$version]($style) "
symbol        ="❯λ "
version_format="${raw}"
style         ="italic yellow"
disabled      =false

[git_branch]
format           ="[$symbol]($style)[$branch:$remote_branch]($style) "
symbol           =" "
style            ="italic yellow"
truncation_symbol="⋯"
truncation_length=8
only_attached    =true
disabled         =false

[git_status]
format    ="[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted]($style) "
style     ="italic yellow"
ahead     =" $count ahead [](rosewater) "
behind    =" $count behind [](rosewater) "
staged    =" $count staged [](rosewater) "
modified  =" $count modified [](rosewater) "
untracked =" $count untracked [](rosewater) "
renamed   =" $count renamed [](rosewater) "
deleted   =" $count deleted [](rosewater) "
conflicted="󰦦 $count conflict [](rosewater) "
disabled  =false

####################
##  Right prompt  ##
####################

[cmd_duration]
format           ="[󱫭 $duration](green)"
show_milliseconds=true
disabled         =false

[jobs]
format  ="[$symbol $number bg jobs]($style) "
symbol  =" "
style   ="italic teal"
disabled=false

[direnv]
format      ="[$symbol.env(rc)]($style) "
symbol      =" "
style       ="italic yellow"
detect_files=[ ".envrc", ".env" ]
disabled    =false

[docker_context]
format="[$symbol$context]($style) "
symbol=" "
style="italic blue"
detect_files=[
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
    "compose.yaml",
    "compose.yml",
]
disabled=false

################
##  Palettes  ##
################

[palettes.catppuccin_mocha]
rosewater="#f5e0dc"
flamingo ="#f2cdcd"
pink     ="#f5c2e7"
mauve    ="#cba6f7"
red      ="#f38ba8"
maroon   ="#eba0ac"
peach    ="#fab387"
yellow   ="#f9e2af"
green    ="#a6e3a1"
teal     ="#94e2d5"
sky      ="#89dceb"
sapphire ="#74c7ec"
blue     ="#89b4fa"
lavender ="#b4befe"
text     ="#cdd6f4"
subtext1 ="#bac2de"
subtext0 ="#a6adc8"
overlay2 ="#9399b2"
overlay1 ="#7f849c"
overlay0 ="#6c7086"
surface2 ="#585b70"
surface1 ="#45475a"
surface0 ="#313244"
base     ="#1e1e2e"
mantle   ="#181825"
crust    ="#11111b"

##################
##  OS Symbols  ##
##################

[os.symbols]
Alpaquita       =" "
Alpine          =" "
AlmaLinux       =" "
Amazon          =" "
Android         =" "
Arch            =" "
Artix           =" "
CachyOS         =" "
CentOS          =" "
Debian          =" "
DragonFly       =" "
Emscripten      =" "
EndeavourOS     =" "
Fedora          =" "
FreeBSD         =" "
Garuda          ="󰛓 "
Gentoo          =" "
HardenedBSD     ="󰞌 "
Illumos         ="󰈸 "
Kali            =" "
Linux           =" "
Mabox           =" "
Macos           =" "
Manjaro         =" "
Mariner         =" "
MidnightBSD     =" "
Mint            =" "
NetBSD          =" "
NixOS           =" "
Nobara          =" "
OpenBSD         ="󰈺 "
openSUSE        =" "
OracleLinux     ="󰌷 "
Pop             =" "
Raspbian        =" "
Redhat          =" "
RedHatEnterprise=" "
RockyLinux      =" "
Redox           ="󰀘 "
Solus           ="󰠳 "
SUSE            =" "
Ubuntu          =" "
Unknown         =" "
Void            =" "
Windows         ="󰍲 "
