# Get editor completions based on the config schema
"$schema"='https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette="catppuccin_mocha"
add_newline=true
format="""
$username\
$os\
$hostname\
[](rosewater) \
$directory\
[](rosewater) \
$direnv\
$jobs\
$sudo\
$fill\
$git_branch\
$git_status\
$docker_context\
$python\
$golang\
$rust\
$lua\
$c\
$zig\
$dart\
$swift\
$nodejs\
$haskell\
$character\
"""

right_format="""
$cmd_duration\
"""

[username]
format     ="[╭─$user]($style) "
style_user ="italic green"
style_root ="italic red"
show_always=true

[os]
format  ="[$symbol](rosewater) "
disabled=false

[hostname]
format  ="[$hostname](lavender) "
ssh_only=false

[directory]
format           ="[$path]($style)[$read_only]($read_only_style) "
home_symbol      ="󱂵 Home"
truncation_symbol=" /"
read_only        =" 󰌾"
read_only_style  ="red"
use_os_path_sep  =true
style            ="italic peach"

[direnv]
format      ="[$symbol.env(rc)]($style) [](rosewater) "
symbol      =" "
style       ="italic yellow"
detect_files=[ ".envrc", ".env" ]
disabled    =false

[jobs]
format="[$symbol $number bg jobs]($style) [](rosewater) "
symbol=" "
style ="italic teal"

[sudo]
format  ="[$symbol]($style) [](rosewater) "
style   ="italic mauve"
symbol  ="⋈"
disabled=false

[fill]
symbol=" "

[git_branch]
format           ="[$symbol]($style)[$branch:$remote_branch]($style) [](rosewater) "
symbol           =" "
style            ="italic yellow"
truncation_symbol="⋯"
truncation_length=8
only_attached    =true

[git_status]
format    ="[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted]($style) "
style     ="italic yellow"
ahead     =" $count ahead [](rosewater) "
behind    =" $count behind [](rosewater) "
staged    =" $count staged [](rosewater) "
modified  =" $count modified [](rosewater) "
untracked =" $count untracked [](rosewater) "
renamed   =" $count renamed [](rosewater) "
deleted   =" $count deleted [](rosewater) "
conflicted="󰦦 $count conflict [](rosewater) "

[python]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic teal"

[rust]
format        ="[$symbol$version]($style) "
symbol        ="󱘗 "
version_format="${raw}"
style         ="italic maroon"

[golang]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic sky"

[c]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic flamingo"

[haskell]
format        ="[$symbol$version]($style) "
symbol        ="❯λ "
version_format="${raw}"
style         ="italic yellow"

[lua]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic peach"

[dart]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic sapphire"

[swift]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic red"

[nodejs]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic green"
detect_files  =[ "package-lock.json", "yarn.lock" ]
detect_folders=[ "node_modules" ]

[zig]
format        ="[$symbol$version]($style) "
symbol        =" "
version_format="${raw}"
style         ="italic flamingo"

[docker_context]
format="[$symbol$context]($style) "
symbol=" "
style="italic blue"
detect_files=[
    "docker-compose.yml",
    "docker-compose.yaml",
    "Dockerfile",
    "compose.yaml",
    "compose.yml",
]
disabled=false

[character]
format        ="\n$symbol "
success_symbol="[╰─ ❯](green)"
error_symbol  ="[╰─](green)[ ❯](red)"
vimcmd_symbol ="[╰─ ❯](dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol="R1"
vimcmd_replace_symbol    ="R"
vimcmd_visual_symbol     ="V"

[cmd_duration]
format           ="[󱫭 $duration](green)"
show_milliseconds=true

[palettes.catppuccin_mocha]
rosewater="#f5e0dc"
flamingo ="#f2cdcd"
pink     ="#f5c2e7"
mauve    ="#cba6f7"
red      ="#f38ba8"
maroon   ="#eba0ac"
peach    ="#fab387"
yellow   ="#f9e2af"
green    ="#a6e3a1"
teal     ="#94e2d5"
sky      ="#89dceb"
sapphire ="#74c7ec"
blue     ="#89b4fa"
lavender ="#b4befe"
text     ="#cdd6f4"
subtext1 ="#bac2de"
subtext0 ="#a6adc8"
overlay2 ="#9399b2"
overlay1 ="#7f849c"
overlay0 ="#6c7086"
surface2 ="#585b70"
surface1 ="#45475a"
surface0 ="#313244"
base     ="#1e1e2e"
mantle   ="#181825"
crust    ="#11111b"

[os.symbols]
Alpaquita       =" "
Alpine          =" "
AlmaLinux       =" "
Amazon          =" "
Android         =" "
Arch            =" "
Artix           =" "
CachyOS         =" "
CentOS          =" "
Debian          =" "
DragonFly       =" "
Emscripten      =" "
EndeavourOS     =" "
Fedora          =" "
FreeBSD         =" "
Garuda          ="󰛓 "
Gentoo          =" "
HardenedBSD     ="󰞌 "
Illumos         ="󰈸 "
Kali            =" "
Linux           =" "
Mabox           =" "
Macos           =" "
Manjaro         =" "
Mariner         =" "
MidnightBSD     =" "
Mint            =" "
NetBSD          =" "
NixOS           =" "
Nobara          =" "
OpenBSD         ="󰈺 "
openSUSE        =" "
OracleLinux     ="󰌷 "
Pop             =" "
Raspbian        =" "
Redhat          =" "
RedHatEnterprise=" "
RockyLinux      =" "
Redox           ="󰀘 "
Solus           ="󰠳 "
SUSE            =" "
Ubuntu          =" "
Unknown         =" "
Void            =" "
Windows         ="󰍲 "
